baseURL: https://paarthtandon.com
title: paarthtandon
paginate: 5
theme: charlolamode


menu:
    main:
        # - name: Contact
        #   url: contact/
        #   weight: 30
        - name: Projects
          url: projects/
          weight: 2
        - name: Resume
          url: resume/
          weight: 4
        # - name: Blog
        #   url: blog/
        #   weight: 3
        # - name: Categories
        #   url: categories/
        #   weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs


params:
    # author: Paarth Tandon

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: false

    profileMode:
        enabled: true
        title: "Hey, I'm Paarth!"
        subtitle: "Currently, I am a **Data Scientist** at **Bungie**, working on building machine learning models for Destiny 2 and future titles. While I may call the PNW my new home, I will always be a Rhode Islander at heart! I love spending time outdoors, bouldering, and playing guitar. Check out my projects on this site, or feel free to add me on my social media!"
        imageUrl: "/images/profile.jpg"
        imageTitle: profile image
        imageWidth: 300
        imageHeight: 300
    mainSections:
      - resume
      - projects
      - articles

    socialIcons:
        - name: instagram
          url: "https://www.instagram.com/paarth.tandon/"
        - name: github
          url: "https://github.com/paarthtandon"
        - name: linkedin
          url: "https://www.linkedin.com/in/paarthtandon/"
        - name: email
          url: "mailto:ptandoncs@gmail.com"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon2.ico"
          # favicon16x16: "/images/favicon-16x16.png"
          # favicon32x32: "/images/favicon-32x32.png"
          # apple_touch_icon: "/images/apple-touch-icon.png"
          # safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
publishDir: docs
paginate: 100

minify:
    disableXML: true

