baseURL: https://paarthtandon.com
title: paarthtandon
paginate: 5
theme: charlolamode


menu:
    main:
        # - name: Contact
        #   url: contact/
        #   weight: 30
        - name: Personal Projects
          url: projects/
        - name: Resume
          url: resume/
        # - name: Consulting Services
        #   url: consulting/
        #   weight: 4
        # - name: Blog
        #   url: blog/
        #   weight: 3
        # - name: Categories
        #   url: categories/
        #   weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs


params:
    # author: Paarth Tandon

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: false

    profileMode:
        enabled: true
        title: "Hey, I'm Paarth!"
        subtitle: "I am currently engaged in providing data science and machine learning expertise to multiple clients on an independent basis. Interested in my services? Contact me via email or any of my social media.\n___\nI have specialized skills in applying and fine-tuning LLMs, alongside traditional data science skills.\n___\nPreviously, I built anti-cheat detections using machine learning for Destiny 2 and future titles at Bungie. I also worked on a real-time NLP service at Moody's Analytics.\n___\nI love spending time outdoors, bouldering, and playing guitar. Check out some of my personal projects on this site, or feel free to add me on my social media!"
        imageUrl: "/images/profile.jpg"
        imageTitle: profile image
        imageWidth: 300
        imageHeight: 300
    mainSections:
      - resume
      - projects
      - articles

    socialIcons:
        - name: instagram
          url: "https://www.instagram.com/paarth.tandon/"
        - name: github
          url: "https://github.com/paarthtandon"
        - name: linkedin
          url: "https://www.linkedin.com/in/paarthtandon/"
        - name: email
          url: "mailto:ptandoncs@gmail.com"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon2.ico"
          # favicon16x16: "/images/favicon-16x16.png"
          # favicon32x32: "/images/favicon-32x32.png"
          # apple_touch_icon: "/images/apple-touch-icon.png"
          # safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
publishDir: docs
paginate: 100

minify:
    disableXML: true

