baseURL: https://paarthtandon.com
title: paarthtandon
paginate: 5
theme: charlolamode


menu:
    main:
        # - name: Contact
        #   url: contact/
        #   weight: 30
        - name: Technical Projects
          url: projects/
          weight: 1
        - name: Resume  
          url: resume/
          weight: 2
        # - name: Photography
        #   url: photography/
        #   weight: 3
        # - name: Consulting Services
        #   url: consulting/
        #   weight: 4
        # - name: Blog
        #   url: blog/
        #   weight: 3
        # - name: Categories
        #   url: categories/
        #   weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs


params:
    # author: Paarth Tandon

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: false

    profileMode:
        enabled: true
        title: "Hey, I'm Paarth!"
        subtitle: "Currently, I am developing ML/AI features at Meltwater in San Francisco.\n___\nPreviously, I detected bad actors using NLP and social graphs at Intorqa, built ML based anti-cheat for Destiny 2 at Bungie, and developed a real-time NLP service at Moody's Analytics.\n___\nI love spending time outdoors, bouldering, film photography, and playing guitar. Check out my projects on this site and feel free to add me on social media!"
        imageUrl: "/images/profile.jpg"
        imageTitle: profile image
        imageWidth: 300
        imageHeight: 300
    mainSections:
      - resume
      - projects
      - articles

    socialIcons:
        - name: instagram
          url: "https://www.instagram.com/paarth.tandon/"
        - name: github
          url: "https://github.com/paarthtandon"
        - name: linkedin
          url: "https://www.linkedin.com/in/paarthtandon/"
        - name: email
          url: "mailto:ptandoncs@gmail.com"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon2.ico"
          # favicon16x16: "/images/favicon-16x16.png"
          # favicon32x32: "/images/favicon-32x32.png"
          # apple_touch_icon: "/images/apple-touch-icon.png"
          # safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
publishDir: docs
paginate: 100

minify:
    disableXML: true

